### ISSUE TITLE
Recreate Log as CSV rather than TXT

### ISSUE THREAD

**Issue by ulysses-ai** [b-eastwood/hvir-calc-py#1]
As discussed, reconfigure the log file as a csv with all of the quality data for the Power BI visualisation

[New Log as a CSV.xlsx](https://github.com/b-eastwood/hvir-calc-py/files/3930578/New.Log.as.a.CSV.xlsx)

**Comment by ed-arrb** [comment]
Issue resolved, now if the logfile is specified as a. csv.  Via `-l data/logfile.csv` the logfile will be written as a csv as per the example xlsx file provide. If the logfile is set as a .txt, a txt version with the old format will be written instead.

**Comment by ulysses-ai** [comment]
Thanks Ed.

Bug:
[cid:image001.png@01D5AE8C.FE2FD620]

Ulysses Ai
MPubPol, MEng (Sustainable Energy), BSc (Physics), Dip (Leadership & Mgmt)
Senior Professional Leader, Asset Management
[cid:image002.png@01D5AE8C.FE357B70]
80a Turner St, Port Melbourne, VIC 3207, Australia
M: +61 448 122 641
ulysses.ai@arrb.com.au | arrb.com.au<http://www.arrb.com.au>
[cid:image007.png@01D5AE8C.FE357B70]<http://www.facebook.com/ARRBGroup>
[cid:image008.png@01D5AE8C.FE357B70]<http://www.linkedin.com/company/arrb-group>
[cid:image009.png@01D5AE8C.FE357B70]<http://www.twitter.com/ARRBGroup>
[cid:image010.png@01D5AE8C.FE357B70]<http://www.youtube.com/user/ARRBGroup>
________________________________
Legal Note: This email and any files transmitted with it are solely intended for the use of the addressee(s) and may contain information that is confidential and privileged. If you receive this email in error, please advise us by return email immediately. Please also disregard the contents of the email, delete it and destroy any copies immediately.
